-- 코드를 작성해주세요
SELECT SUM(hg.SCORE) AS SCORE, 
       he.EMP_NO, he.EMP_NAME, he.POSITION, he.EMAIL
FROM HR_EMPLOYEES he
JOIN HR_GRADE hg ON he.EMP_NO = hg.EMP_NO
WHERE hg.YEAR = "2022"
GROUP BY he.EMP_NO
ORDER BY SCORE DESC
LIMIT 1;